/**
 * @fileoverview SQLite State Module
 *
 * Generates Lua code for persistent NPC state using an embedded SQLite
 * database. Because StarMade's Lua engine (LuaJ) has access to Java,
 * the SQLite integration is done via Java's SQLite JDBC driver exposed
 * through luajava.
 *
 * This generates helper Lua functions at the top of the script that
 * the dialog builder can reference in custom hook bodies.
 *
 * Usage:
 *   const db = new SqliteState('/path/to/npc_state.db');
 *   db.defineTable('quests', { player: 'TEXT', quest_id: 'INTEGER', done: 'INTEGER DEFAULT 0' });
 *   db.defineTable('interactions', { player: 'TEXT', count: 'INTEGER DEFAULT 0' });
 *
 *   // In a hook body:
 *   db.hookGet('quests', 'done', 'dialogObject:getOwnName()', '0')
 *   db.hookSet('quests', 'done', '1', 'dialogObject:getOwnName()')
 *   db.hookIncrement('interactions', 'count', 'dialogObject:getOwnName()')
 *
 * @author InitSysRev
 * @version 1.0.0
 */

export interface TableSchema {
  [column: string]: string; // column name → SQL type + constraints
}

export interface SqliteStateOptions {
  /** Absolute path to the SQLite database file on the server. */
  dbPath: string;
  /** Java SQLite JDBC driver class name. Defaults to 'org.sqlite.JDBC'. */
  driverClass?: string;
  /** Lua variable name for the Connection object. Defaults to '_npcDb'. */
  connVar?: string;
}

/**
 * Generates Lua SQLite helper code for persistent NPC state.
 *
 * The generated code uses LuaJava to access Java's JDBC API directly.
 * The SQLite JDBC driver (sqlite-jdbc) must be on the StarMade classpath.
 */
export class SqliteState {
  private readonly dbPath: string;
  private readonly driverClass: string;
  private readonly connVar: string;
  private readonly tables = new Map<string, TableSchema>();

  constructor(options: SqliteStateOptions) {
    this.dbPath = options.dbPath;
    this.driverClass = options.driverClass ?? 'org.sqlite.JDBC';
    this.connVar = options.connVar ?? '_npcDb';
  }

  /**
   * Register a table schema. The table is created if it doesn't exist.
   *
   * @example
   * db.defineTable('quests', {
   *   player:   'TEXT NOT NULL',
   *   quest_id: 'INTEGER NOT NULL',
   *   done:     'INTEGER DEFAULT 0',
   * })
   */
  defineTable(name: string, schema: TableSchema): this {
    this.tables.set(name, schema);
    return this;
  }

  /**
   * Generates the Lua initialization block:
   * - Loads the JDBC driver
   * - Opens the connection
   * - Creates all declared tables
   *
   * Paste this at the top of the script (before `create()`).
   */
  emitInit(): string {
    const lines: string[] = [];
    lines.push(`-- SQLite persistent state (generated by StarMade-NPCCreator)`);
    lines.push(`local _DriverManager = luajava.bindClass("java.sql.DriverManager")`);
    lines.push(`local _ok, _err = pcall(function()`);
    lines.push(`  luajava.bindClass("${this.driverClass}")`);
    lines.push(`end)`);
    lines.push(`${this.connVar} = _DriverManager:getConnection("jdbc:sqlite:${this.dbPath}")`);
    lines.push(``);
    lines.push(`-- Create tables`);
    for (const [table, schema] of this.tables) {
      const cols = Object.entries(schema)
        .map(([col, def]) => `  ${col} ${def}`)
        .join(',\n');
      lines.push(`do`);
      lines.push(`  local _stmt = ${this.connVar}:createStatement()`);
      lines.push(`  _stmt:execute([[CREATE TABLE IF NOT EXISTS ${table} (`);
      lines.push(cols);
      lines.push(`  )]])`);
      lines.push(`  _stmt:close()`);
      lines.push(`end`);
      lines.push(``);
    }

    // Helper functions
    lines.push(`-- Helper: execute a prepared statement (no result)`);
    lines.push(`local function _dbExec(sql, ...)`);
    lines.push(`  local ps = ${this.connVar}:prepareStatement(sql)`);
    lines.push(`  local args = {...}`);
    lines.push(`  for i, v in ipairs(args) do`);
    lines.push(`    ps:setObject(i, v)`);
    lines.push(`  end`);
    lines.push(`  ps:executeUpdate()`);
    lines.push(`  ps:close()`);
    lines.push(`end`);
    lines.push(``);
    lines.push(`-- Helper: query a single value (returns nil if no row)`);
    lines.push(`local function _dbGet(sql, ...)`);
    lines.push(`  local ps = ${this.connVar}:prepareStatement(sql)`);
    lines.push(`  local args = {...}`);
    lines.push(`  for i, v in ipairs(args) do`);
    lines.push(`    ps:setObject(i, v)`);
    lines.push(`  end`);
    lines.push(`  local rs = ps:executeQuery()`);
    lines.push(`  local result = nil`);
    lines.push(`  if rs:next() then result = rs:getObject(1) end`);
    lines.push(`  rs:close()`);
    lines.push(`  ps:close()`);
    lines.push(`  return result`);
    lines.push(`end`);
    lines.push(``);
    lines.push(`-- Helper: upsert (INSERT OR REPLACE) a row by player key`);
    lines.push(`local function _dbUpsert(table, keyCol, keyVal, col, val)`);
    lines.push(`  local existing = _dbGet("SELECT " .. col .. " FROM " .. table .. " WHERE " .. keyCol .. " = ?", keyVal)`);
    lines.push(`  if existing == nil then`);
    lines.push(`    _dbExec("INSERT INTO " .. table .. " (" .. keyCol .. ", " .. col .. ") VALUES (?, ?)", keyVal, val)`);
    lines.push(`  else`);
    lines.push(`    _dbExec("UPDATE " .. table .. " SET " .. col .. " = ? WHERE " .. keyCol .. " = ?", val, keyVal)`);
    lines.push(`  end`);
    lines.push(`end`);
    lines.push(``);
    lines.push(`-- Helper: increment a numeric column (INSERT row if absent)`);
    lines.push(`local function _dbIncrement(table, keyCol, keyVal, col, amount)`);
    lines.push(`  amount = amount or 1`);
    lines.push(`  local cur = _dbGet("SELECT " .. col .. " FROM " .. table .. " WHERE " .. keyCol .. " = ?", keyVal)`);
    lines.push(`  if cur == nil then`);
    lines.push(`    _dbExec("INSERT INTO " .. table .. " (" .. keyCol .. ", " .. col .. ") VALUES (?, ?)", keyVal, amount)`);
    lines.push(`  else`);
    lines.push(`    _dbExec("UPDATE " .. table .. " SET " .. col .. " = " .. col .. " + ? WHERE " .. keyCol .. " = ?", amount, keyVal)`);
    lines.push(`  end`);
    lines.push(`end`);

    return lines.join('\n');
  }

  /**
   * Returns a Lua expression that reads a value from the DB.
   *
   * @param table    Table name
   * @param col      Column to read
   * @param keyExpr  Lua expression for the key value (e.g. `dialogObject:getOwnName()`)
   * @param defaultExpr Default Lua expression if not found (e.g. `"0"`, `"nil"`)
   *
   * @example
   * // In a hook body:
   * const questDone = db.exprGet('quests', 'done', 'dialogObject:getOwnName()', '0');
   * body: [
   *   `local done = ${questDone}`,
   *   'if done == "1" then return 0 end',
   *   'return -1',
   * ]
   */
  exprGet(table: string, col: string, keyExpr: string, defaultExpr = 'nil'): string {
    return `(_dbGet("SELECT ${col} FROM ${table} WHERE player = ?", ${keyExpr}) or ${defaultExpr})`;
  }

  /**
   * Returns Lua lines that set a value in the DB for the current player.
   *
   * @param table    Table name
   * @param col      Column to set
   * @param valExpr  Lua expression for the new value (e.g. `"1"`, `"myVar"`)
   * @param keyExpr  Lua expression for the player key
   */
  linesSet(table: string, col: string, valExpr: string, keyExpr: string): string[] {
    return [`_dbUpsert("${table}", "player", ${keyExpr}, "${col}", ${valExpr})`];
  }

  /**
   * Returns Lua lines that increment a numeric column for the current player.
   */
  linesIncrement(table: string, col: string, keyExpr: string, amount = 1): string[] {
    return [`_dbIncrement("${table}", "player", ${keyExpr}, "${col}", ${amount})`];
  }

  /**
   * Returns a hook body that:
   * 1. Reads a flag from the DB
   * 2. If the flag equals `successValue`, returns 0 (success)
   * 3. Otherwise sets the flag and returns 0
   *
   * Useful for "one-time" quests or interactions.
   */
  bodyCheckAndSet(
    table: string,
    col: string,
    successValue: string,
    keyExpr: string,
  ): string[] {
    return [
      `local _val = ${this.exprGet(table, col, keyExpr, '"0"')}`,
      `if _val == "${successValue}" then return 0 end`,
      ...this.linesSet(table, col, `"${successValue}"`, keyExpr),
      `return 0`,
    ];
  }
}
