// generator/emitter.js — Generate the full Lua script from _state

import { _state } from './state.js';
import { textExpr, luaStringLiteral } from './helpers.js';

/**
 * Emit the complete Lua script for the current generator state.
 *
 * @param {string} scriptName Human-readable script name for the header.
 * @returns {string} Full Lua script.
 */
export function emitLua(scriptName) {
  const lines = [];

  lines.push(`--[[`);
  lines.push(`  NPC Dialog Script: ${scriptName}`);
  lines.push(`  Generated by StarMade NPC Creator`);
  lines.push(`--]]`);
  lines.push('');

  // User variables
  if (_state.luaVars.length > 0) {
    lines.push('-- User variables');
    for (const v of _state.luaVars) {
      lines.push(`${v.name} = ${luaVarLiteral(v.mode, v.value)};`);
    }
    lines.push('');
  }

  // HSQLDB persistent state
  const needsHsql = _state.usesHsqlMemory || _state.usesQuestTable || _state.usesReputation ||
                    _state.usesCooldowns  || _state.usesShopStock  || _state.usesWorldState ||
                    _state.dbTables.size > 0;

  if (needsHsql) {
    lines.push('-- HSQLDB persistent state (world-aware, auto-creates DB and tables)');
    lines.push('local _ServerConfig  = luajava.bindClass("org.schema.game.server.data.ServerConfig")');
    lines.push('local _worldName     = _ServerConfig.WORLD:getString():lower()');
    lines.push('local _npcDbUrl      = "jdbc:hsqldb:file:./server-database/" .. _worldName .. "/npc_data/npc_state;shutdown=false;hsqldb.write_delay=false"');
    lines.push('luajava.bindClass("org.hsqldb.jdbc.JDBCDriver")');
    lines.push('local _DriverManager = luajava.bindClass("java.sql.DriverManager")');
    lines.push('local _npcDb         = _DriverManager.getConnection(_npcDbUrl, "SA", "")');
    lines.push('_npcDb:setAutoCommit(true)');
    lines.push('');

    if (_state.usesQuestTable)  lines.push(...tableBlock('npc_quests',
      '"player VARCHAR(255) NOT NULL, quest_id VARCHAR(255) NOT NULL, ' +
      'status VARCHAR(32) NOT NULL DEFAULT \'\'none\'\', step INTEGER NOT NULL DEFAULT 0, ' +
      'started_at BIGINT NOT NULL DEFAULT 0, completed_at BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (player, quest_id))"'));

    if (_state.usesHsqlMemory)  lines.push(...tableBlock('npc_memory',
      '"player VARCHAR(255) NOT NULL, k VARCHAR(255) NOT NULL, v LONGVARCHAR, PRIMARY KEY(player, k)"'));

    for (const [tbl, { cols }] of _state.dbTables.entries())
      lines.push(...tableBlock(tbl, `"${cols}"`));

    if (_state.dbTables.size > 0) lines.push('');

    // Generic DB helpers
    lines.push(...DB_HELPERS);
    lines.push('');

    if (_state.usesQuestTable)  lines.push(...QUEST_HELPERS);
    if (_state.usesHsqlMemory)  lines.push(...MEMORY_HELPERS);
    if (_state.usesReputation)  lines.push(...repTable(), ...REP_HELPERS);
    if (_state.usesCooldowns)   lines.push(...cooldownTable(), ...COOLDOWN_HELPERS);
    if (_state.usesShopStock)   lines.push(...stockTable(), ...STOCK_HELPERS);
    if (_state.usesWorldState)  lines.push(...worldTable(), ...WORLD_HELPERS);
  }

  // Hook functions
  if (_state.hooks.size > 0) {
    lines.push('-- Hook functions');
    for (const [fn, hook] of _state.hooks) {
      const body     = Array.isArray(hook) ? hook : hook.body;
      const disabled = !Array.isArray(hook) && hook.disabled;
      const comment  = !Array.isArray(hook) ? hook.comment : null;

      if (comment) {
        // Emit block comment above the hook function
        for (const cline of comment.split('\n')) {
          lines.push(`-- ${cline}`);
        }
      }

      if (disabled) {
        // Disabled hook: the block comment marker is enough and keeps Lua cleaner.
        lines.push(`--[[ DISABLED`);
        lines.push(`function ${fn}(dialogObject)`);
        for (const l of body) lines.push(`  ${l}`);
        lines.push(`end`);
        lines.push(`--]]`);
      } else {
        lines.push(`function ${fn}(dialogObject)`);
        for (const l of body) lines.push(`  ${l}`);
        lines.push('end');
      }
      lines.push('');
    }
  }

  // create()
  lines.push('function create(dialogObject, bindings)');
  lines.push('');
  lines.push('  local dSys = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogSystem", dialogObject)');
  lines.push('  local factory = dSys:getFactory(bindings)');
  lines.push('  local TextEntry = "org.schema.game.common.data.player.dialog.TextEntry"');
  lines.push('  local HookLua   = "org.schema.game.common.data.player.dialog.DialogTextEntryHookLua"');
  lines.push('');

  const isHookDisabled = (fn) => {
    const hook = _state.hooks.get(fn);
    return !!hook && !Array.isArray(hook) && !!hook.disabled;
  };
  const disabledLine = (line) => `  -- [DISABLED] ${line.trim()}`;

  // Hook instances — keep disabled ones as commented Lua, not silently removed
  const allHooks = Array.from(new Set(_state.nodes.filter(n => n.hook).map(n => n.hook)));
  if (allHooks.length > 0) {
    lines.push('  -- Hook instances');
    for (const fn of allHooks) {
      const line = `local hook_${fn} = luajava.newInstance(HookLua, "${fn}", {})`;
      if (isHookDisabled(fn)) lines.push(disabledLine(line));
      else lines.push(`  ${line}`);
    }
    lines.push('');
  }

  // Node declarations
  lines.push('  -- Dialog nodes');
  for (const node of _state.nodes) {
    if (node.comment) {
      // Inline comment above the node declaration
      for (const cline of node.comment.split('\n')) {
        lines.push(`  -- ${cline}`);
      }
    }
    const line = `local ${node.varName} = luajava.newInstance(TextEntry, ${textExpr(node.text)}, ${node.ms})`;
    if (node.disabled) {
      // Disabled node: preserve exact generated Lua as a comment
      lines.push(disabledLine(line));
    } else {
      lines.push(`  ${line}`);
    }
  }
  lines.push('');

  // Root
  const rootNode = _state.nodes.find(n => n.varName === _state.rootVar);
  const rootLine = `factory:setRootEntry(${_state.rootVar})`;
  if (rootNode?.disabled) lines.push(disabledLine(rootLine));
  else lines.push(`  ${rootLine}`);
  lines.push('');

  // Hooks — disabled node/hook wiring is preserved as commented Lua
  const nodesWithHooks = _state.nodes.filter(n => n.hook);
  if (nodesWithHooks.length > 0) {
    lines.push('  -- Attach hooks');
    for (const n of nodesWithHooks) {
      const line = `${n.varName}:setHook(hook_${n.hook})`;
      if (n.disabled || isHookDisabled(n.hook)) lines.push(disabledLine(line));
      else lines.push(`  ${line}`);
    }
    lines.push('');
  }

  // Reactions — disabled source/target wiring is preserved as commented Lua
  const nodesWithReactions = _state.nodes.filter(n => n.reactions.length > 0);
  if (nodesWithReactions.length > 0) {
    lines.push('  -- Hook reactions');
    for (const n of nodesWithReactions) {
      for (const r of n.reactions) {
        const tgt = typeof r.target === 'string' ? r.target : r.target?.varName ?? r.target;
        const targetNode = _state.nodes.find(nd => nd.varName === tgt);
        const line = `${n.varName}:addReaction(hook_${n.hook}, ${r.code}, ${tgt})`;
        if (n.disabled || targetNode?.disabled || isHookDisabled(n.hook)) lines.push(disabledLine(line));
        else lines.push(`  ${line}`);
      }
    }
    lines.push('');
  }

  // Choices — choices leading to disabled nodes, or disabled themselves, are preserved as commented Lua
  const nodesWithChoices = _state.nodes.filter(n => n.choices.length > 0);
  if (nodesWithChoices.length > 0) {
    lines.push('  -- Player choices');
    for (const n of nodesWithChoices) {
      for (const c of n.choices) {
        const tgt = typeof c.targetVarName === 'string' ? c.targetVarName : c.targetVarName?.varName ?? c.targetVarName;
        const targetNode = _state.nodes.find(nd => nd.varName === tgt);
        const line = `${n.varName}:add(${tgt}, ${textExpr(c.label)})`;
        if (n.disabled || c.disabled || targetNode?.disabled) lines.push(disabledLine(line));
        else lines.push(`  ${line}`);
      }
    }
    lines.push('');
  }

  lines.push('  dSys:add(factory)');
  lines.push('  return dSys');
  lines.push('');
  lines.push('end');

  return lines.join('\n');
}

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Convert a user variable value into Lua source text. */
function luaVarLiteral(mode, value) {
  if (mode === 'text')   return `"${String(value || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  if (mode === 'number') return String(Number(value) || 0);
  return String(value || 'nil');
}

/** Emit a helper block that creates an HSQLDB table if missing. */
function tableBlock(name, colsDef) {
  return [
    `do`,
    `  local _s = _npcDb:createStatement()`,
    `  _s:execute("CREATE CACHED TABLE IF NOT EXISTS ${name} (" ..`,
    `    ${colsDef} ..`,
    `  ")")`,
    `  _s:close()`,
    `end`,
    '',
  ];
}

/** Emit the reputation table definition. */
function repTable() {
  return tableBlock('npc_reputation',
    '"player VARCHAR(255) NOT NULL, npc_id VARCHAR(255) NOT NULL, score INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (player, npc_id))"');
}

/** Emit the cooldown table definition. */
function cooldownTable() {
  return tableBlock('npc_cooldowns',
    '"player VARCHAR(255) NOT NULL, action_id VARCHAR(255) NOT NULL, expires_at BIGINT NOT NULL DEFAULT 0, PRIMARY KEY (player, action_id))"');
}

/** Emit the shop stock table definition. */
function stockTable() {
  return tableBlock('npc_shop_stock',
    '"shop_id VARCHAR(255) NOT NULL, item_type INTEGER NOT NULL, quantity INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (shop_id, item_type))"');
}

/** Emit the world-state table definition. */
function worldTable() {
  return tableBlock('npc_world_state',
    '"key VARCHAR(255) PRIMARY KEY, value LONGVARCHAR)"');
}

// ── Lua helper code blocks ────────────────────────────────────────────────────

const DB_HELPERS = [
  'local function _dbGet(sql, ...)',
  '  local ps = _npcDb:prepareStatement(sql)',
  '  local a = {...}; for i,v in ipairs(a) do ps:setObject(i, v) end',
  '  local rs = ps:executeQuery(); local r = nil',
  '  if rs:next() then r = rs:getObject(1) end',
  '  rs:close(); ps:close(); return r',
  'end',
  'local function _dbExec(sql, ...)',
  '  local ps = _npcDb:prepareStatement(sql)',
  '  local a = {...}; for i,v in ipairs(a) do ps:setObject(i, v) end',
  '  ps:executeUpdate(); ps:close()',
  'end',
  'local function _dbUpsert(t, kc, kv, col, val)',
  '  _dbExec("MERGE INTO "..t.." AS tgt USING (VALUES(CAST(? AS VARCHAR(255)),CAST(? AS LONGVARCHAR))) AS src(k,v) ON tgt."..kc.."=src.k WHEN MATCHED THEN UPDATE SET "..col.."=src.v WHEN NOT MATCHED THEN INSERT ("..kc..","..col..") VALUES(src.k,src.v)", kv, val)',
  'end',
  'local function _dbIncrement(t, kc, kv, col, n)',
  '  n = n or 1',
  '  local cur = _dbGet("SELECT "..col.." FROM "..t.." WHERE "..kc.."=?", kv)',
  '  if cur == nil then _dbExec("INSERT INTO "..t.."("..kc..","..col..") VALUES(?,?)", kv, n)',
  '  else _dbExec("UPDATE "..t.." SET "..col.."="..col.." + ? WHERE "..kc.."=?", n, kv) end',
  'end',
  'local function _dbGetPlayerValue(t, col, player, def)',
  '  local v = _dbGet("SELECT "..col.." FROM "..t.." WHERE player=?", player)',
  '  return v ~= nil and v or def',
  'end',
  'local function _dbGetPlayerNumber(t, col, player, def)',
  '  local n = tonumber(_dbGetPlayerValue(t, col, player, def))',
  '  return n ~= nil and n or (tonumber(def) or 0)',
  'end',
  'local function _dbGetPlayerText(t, col, player, def)',
  '  local v = _dbGetPlayerValue(t, col, player, def)',
  '  return v ~= nil and tostring(v) or tostring(def or "")',
  'end',
  'local function _dbHasPlayerRow(t, player)',
  '  return _dbGet("SELECT 1 FROM "..t.." WHERE player=?", player) ~= nil',
  'end',
];

const QUEST_HELPERS = [
  '-- Quest helpers (npc_quests)',
  'local function _questSet(player, qid, status, step)',
  '  local now = luajava.bindClass("java.lang.System").currentTimeMillis()',
  '  if _dbGet("SELECT 1 FROM npc_quests WHERE player=? AND quest_id=?", player, qid) == nil then',
  '    _dbExec("INSERT INTO npc_quests(player,quest_id,status,step,started_at,completed_at) VALUES(?,?,?,?,?,0)", player, qid, status, step, now)',
  '  else',
  '    local ca = (status == "complete" or status == "failed") and now or 0',
  '    _dbExec("UPDATE npc_quests SET status=?,step=?,completed_at=? WHERE player=? AND quest_id=?", status, step, ca, player, qid)',
  '  end',
  'end',
  'local function _questStatus(player, qid)',
  '  local v = _dbGet("SELECT status FROM npc_quests WHERE player=? AND quest_id=?", player, qid)',
  '  return v ~= nil and tostring(v) or "none"',
  'end',
  'local function _questStep(player, qid)',
  '  local v = _dbGet("SELECT step FROM npc_quests WHERE player=? AND quest_id=?", player, qid)',
  '  return v ~= nil and tonumber(v) or 0',
  'end',
  '',
];

const MEMORY_HELPERS = [
  '-- Generic memory helpers (npc_memory)',
  'local function _memSet(player, key, val)',
  '  _dbExec("MERGE INTO npc_memory AS m USING (VALUES(CAST(? AS VARCHAR(255)),CAST(? AS VARCHAR(255)),CAST(? AS LONGVARCHAR))) AS v(p,k,vv) ON m.player=v.p AND m.k=v.k WHEN MATCHED THEN UPDATE SET v=v.vv WHEN NOT MATCHED THEN INSERT(player,k,v) VALUES(v.p,v.k,v.vv)", player, key, tostring(val))',
  'end',
  'local function _memGetText(player, key, def)',
  '  local v = _dbGet("SELECT v FROM npc_memory WHERE player=? AND k=?", player, key)',
  '  return v ~= nil and tostring(v) or tostring(def or "")',
  'end',
  'local function _memGetNumber(player, key, def)',
  '  local n = tonumber(_memGetText(player, key, tostring(def)))',
  '  return n ~= nil and n or (tonumber(def) or 0)',
  'end',
  'local function _memHas(player, key)',
  '  return _dbGet("SELECT 1 FROM npc_memory WHERE player=? AND k=?", player, key) ~= nil',
  'end',
  'local function _memIncrement(player, key, n)',
  '  n = n or 1; _memSet(player, key, _memGetNumber(player, key, 0) + n)',
  'end',
  'local function _flagSet(player, flagName, value)',
  '  _memSet(player, "flag:"..flagName, value and "1" or "0")',
  'end',
  'local function _flagGet(player, flagName)',
  '  return _memGetText(player, "flag:"..flagName, "0") == "1"',
  'end',
  '',
];

const REP_HELPERS = [
  'local function _repGet(player, npcId)',
  '  local v = _dbGet("SELECT score FROM npc_reputation WHERE player=? AND npc_id=?", player, npcId)',
  '  return v ~= nil and tonumber(v) or 0',
  'end',
  'local function _repAdd(player, npcId, delta)',
  '  if _dbGet("SELECT 1 FROM npc_reputation WHERE player=? AND npc_id=?", player, npcId) == nil then',
  '    _dbExec("INSERT INTO npc_reputation(player,npc_id,score) VALUES(?,?,?)", player, npcId, delta)',
  '  else _dbExec("UPDATE npc_reputation SET score=score+? WHERE player=? AND npc_id=?", delta, player, npcId) end',
  'end',
  'local function _repSet(player, npcId, value)',
  '  if _dbGet("SELECT 1 FROM npc_reputation WHERE player=? AND npc_id=?", player, npcId) == nil then',
  '    _dbExec("INSERT INTO npc_reputation(player,npc_id,score) VALUES(?,?,?)", player, npcId, value)',
  '  else _dbExec("UPDATE npc_reputation SET score=? WHERE player=? AND npc_id=?", value, player, npcId) end',
  'end',
  '',
];

const COOLDOWN_HELPERS = [
  'local function _cooldownSet(player, actionId, durationMs)',
  '  local now = luajava.bindClass("java.lang.System").currentTimeMillis()',
  '  local exp = now + durationMs',
  '  if _dbGet("SELECT 1 FROM npc_cooldowns WHERE player=? AND action_id=?", player, actionId) == nil then',
  '    _dbExec("INSERT INTO npc_cooldowns(player,action_id,expires_at) VALUES(?,?,?)", player, actionId, exp)',
  '  else _dbExec("UPDATE npc_cooldowns SET expires_at=? WHERE player=? AND action_id=?", exp, player, actionId) end',
  'end',
  'local function _cooldownActive(player, actionId)',
  '  local now = luajava.bindClass("java.lang.System").currentTimeMillis()',
  '  local exp = _dbGet("SELECT expires_at FROM npc_cooldowns WHERE player=? AND action_id=?", player, actionId)',
  '  return exp ~= nil and tonumber(exp) > now',
  'end',
  'local function _cooldownRemaining(player, actionId)',
  '  local now = luajava.bindClass("java.lang.System").currentTimeMillis()',
  '  local exp = _dbGet("SELECT expires_at FROM npc_cooldowns WHERE player=? AND action_id=?", player, actionId)',
  '  if exp == nil then return 0 end',
  '  local r = tonumber(exp) - now; return r > 0 and r or 0',
  'end',
  '',
];

const STOCK_HELPERS = [
  'local function _stockGet(shopId, itemType)',
  '  local v = _dbGet("SELECT quantity FROM npc_shop_stock WHERE shop_id=? AND item_type=?", shopId, itemType)',
  '  return v ~= nil and tonumber(v) or 0',
  'end',
  'local function _stockInit(shopId, itemType, qty)',
  '  if _dbGet("SELECT 1 FROM npc_shop_stock WHERE shop_id=? AND item_type=?", shopId, itemType) == nil then',
  '    _dbExec("INSERT INTO npc_shop_stock(shop_id,item_type,quantity) VALUES(?,?,?)", shopId, itemType, qty)',
  '  end',
  'end',
  'local function _stockTake(shopId, itemType, qty)',
  '  if _stockGet(shopId, itemType) < qty then return false end',
  '  _dbExec("UPDATE npc_shop_stock SET quantity=quantity-? WHERE shop_id=? AND item_type=?", qty, shopId, itemType)',
  '  return true',
  'end',
  'local function _stockAdd(shopId, itemType, qty)',
  '  if _dbGet("SELECT 1 FROM npc_shop_stock WHERE shop_id=? AND item_type=?", shopId, itemType) == nil then',
  '    _dbExec("INSERT INTO npc_shop_stock(shop_id,item_type,quantity) VALUES(?,?,?)", shopId, itemType, qty)',
  '  else _dbExec("UPDATE npc_shop_stock SET quantity=quantity+? WHERE shop_id=? AND item_type=?", qty, shopId, itemType) end',
  'end',
  '',
];

const WORLD_HELPERS = [
  'local function _worldGet(key, def)',
  '  local v = _dbGet("SELECT value FROM npc_world_state WHERE key=?", key)',
  '  return v ~= nil and tostring(v) or tostring(def or "")',
  'end',
  'local function _worldGetNumber(key, def)',
  '  local n = tonumber(_worldGet(key, tostring(def)))',
  '  return n ~= nil and n or (tonumber(def) or 0)',
  'end',
  'local function _worldSet(key, value)',
  '  _dbExec("MERGE INTO npc_world_state AS w USING (VALUES(CAST(? AS VARCHAR(255)),CAST(? AS LONGVARCHAR))) AS v(k,vv) ON w.key=v.k WHEN MATCHED THEN UPDATE SET value=v.vv WHEN NOT MATCHED THEN INSERT(key,value) VALUES(v.k,v.vv)", key, tostring(value))',
  'end',
  '',
];
