--[[
  Trading Guild merchant NPC
  Generated by StarMade-NPCCreator
  Script name: simple-merchant
--]]

-- Hook functions
function hireHookFunc_50000(dialogObject)
  return dialogObject:hireConverationPartner();
end

function giveLaserHookFunc_100000(dialogObject)
  return dialogObject:giveLaserWeapon(100000);
end

function giveSniperHookFunc_500000(dialogObject)
  return dialogObject:giveSniperRifle(500000);
end

function giveRocketHookFunc_1000000(dialogObject)
  return dialogObject:giveRocketLauncher(1000000);
end

function giveHelmetHookFunc_50000(dialogObject)
  return dialogObject:giveHelmet(50000);
end

function giveGrappleHookFunc_100000(dialogObject)
  return dialogObject:giveGrappleBeam(100000);
end

function giveFlashHookFunc_3000(dialogObject)
  return dialogObject:giveFlashLight(3000);
end

function create(dialogObject, bindings)

  -- Bind Java dialog classes
  local dSys = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogSystem", dialogObject)
  local factory = dSys:getFactory(bindings)

  -- Hook instances
  local hook_hireHookFunc_50000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "hireHookFunc_50000", {})
  local hook_giveLaserHookFunc_100000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "giveLaserHookFunc_100000", {})
  local hook_giveSniperHookFunc_500000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "giveSniperHookFunc_500000", {})
  local hook_giveRocketHookFunc_1000000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "giveRocketHookFunc_1000000", {})
  local hook_giveHelmetHookFunc_50000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "giveHelmetHookFunc_50000", {})
  local hook_giveGrappleHookFunc_100000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "giveGrappleHookFunc_100000", {})
  local hook_giveFlashHookFunc_3000 = luajava.newInstance("org.schema.game.common.data.player.dialog.DialogTextEntryHookLua", "giveFlashHookFunc_3000", {})

  -- Dialog nodes
  local entry = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Greetings, %s!\n\nI'm %s of %s.\nWhat can I do for you today?", dialogObject:getConverationParterName(), dialogObject:getConverationPartnerAffinity(), dialogObject:getConverationPartnerFactionName()), 2000)
  local entry1 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("[I want to join your team.]"), 2000)
  local entrySuccess2 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("I'm honoured to work with you, commander!"), 2000)
  local entryFailed3 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed24 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entryFailed35 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("I'm not doing that."), 2000)
  local entry6 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("[I need a weapon.]"), 2000)
  local entry7 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Laser Pistol (100 000 credits)"), 2000)
  local entrySuccess8 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Thank you!"), 2000)
  local entryFailed9 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed210 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entry11 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sniper Rifle (500 000 credits)"), 2000)
  local entrySuccess12 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Thank you!"), 2000)
  local entryFailed13 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed214 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entry15 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Rocket Launcher (1 000 000 credits)"), 2000)
  local entrySuccess16 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Thank you!"), 2000)
  local entryFailed17 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed218 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entry19 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Never mind."), 2000)
  local entry20 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("[I need equipment.]"), 2000)
  local entry21 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Helmet (50 000 credits)"), 2000)
  local entrySuccess22 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Thank you!"), 2000)
  local entryFailed23 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed224 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entry25 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Grapple Beam (100 000 credits)"), 2000)
  local entrySuccess26 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Thank you!"), 2000)
  local entryFailed27 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed228 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entry29 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Flashlight (3 000 credits)"), 2000)
  local entrySuccess30 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Thank you!"), 2000)
  local entryFailed31 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("You don't have enough money!"), 2000)
  local entryFailed232 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Sorry, your inventory is full!"), 2000)
  local entry33 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("Never mind."), 2000)
  local entry34 = luajava.newInstance("org.schema.game.common.data.player.dialog.TextEntry", dialogObject:format("[Goodbye.]"), 2000)

  -- Root entry
  factory:setRootEntry(entry)

  -- Attach hooks
  entry1:setHook(hook_hireHookFunc_50000)
  entry7:setHook(hook_giveLaserHookFunc_100000)
  entry11:setHook(hook_giveSniperHookFunc_500000)
  entry15:setHook(hook_giveRocketHookFunc_1000000)
  entry21:setHook(hook_giveHelmetHookFunc_50000)
  entry25:setHook(hook_giveGrappleHookFunc_100000)
  entry29:setHook(hook_giveFlashHookFunc_3000)

  -- Hook reactions
  entry1:addReaction(hook_hireHookFunc_50000, 0, entrySuccess2)
  entry1:addReaction(hook_hireHookFunc_50000, -1, entryFailed3)
  entry1:addReaction(hook_hireHookFunc_50000, -2, entryFailed24)
  entry1:addReaction(hook_hireHookFunc_50000, -3, entryFailed35)
  entry7:addReaction(hook_giveLaserHookFunc_100000, 0, entrySuccess8)
  entry7:addReaction(hook_giveLaserHookFunc_100000, -1, entryFailed9)
  entry7:addReaction(hook_giveLaserHookFunc_100000, -2, entryFailed210)
  entry11:addReaction(hook_giveSniperHookFunc_500000, 0, entrySuccess12)
  entry11:addReaction(hook_giveSniperHookFunc_500000, -1, entryFailed13)
  entry11:addReaction(hook_giveSniperHookFunc_500000, -2, entryFailed214)
  entry15:addReaction(hook_giveRocketHookFunc_1000000, 0, entrySuccess16)
  entry15:addReaction(hook_giveRocketHookFunc_1000000, -1, entryFailed17)
  entry15:addReaction(hook_giveRocketHookFunc_1000000, -2, entryFailed218)
  entry21:addReaction(hook_giveHelmetHookFunc_50000, 0, entrySuccess22)
  entry21:addReaction(hook_giveHelmetHookFunc_50000, -1, entryFailed23)
  entry21:addReaction(hook_giveHelmetHookFunc_50000, -2, entryFailed224)
  entry25:addReaction(hook_giveGrappleHookFunc_100000, 0, entrySuccess26)
  entry25:addReaction(hook_giveGrappleHookFunc_100000, -1, entryFailed27)
  entry25:addReaction(hook_giveGrappleHookFunc_100000, -2, entryFailed228)
  entry29:addReaction(hook_giveFlashHookFunc_3000, 0, entrySuccess30)
  entry29:addReaction(hook_giveFlashHookFunc_3000, -1, entryFailed31)
  entry29:addReaction(hook_giveFlashHookFunc_3000, -2, entryFailed232)

  -- Player choices
  entry:add(entry1, dialogObject:format("I want to join your team."))
  entry:add(entry6, dialogObject:format("I need a weapon."))
  entry:add(entry20, dialogObject:format("I need equipment."))
  entry:add(entry34, dialogObject:format("Goodbye."))
  entry6:add(entry7, dialogObject:format("Laser Pistol (100 000 credits)"))
  entry6:add(entry11, dialogObject:format("Sniper Rifle (500 000 credits)"))
  entry6:add(entry15, dialogObject:format("Rocket Launcher (1 000 000 credits)"))
  entry6:add(entry19, dialogObject:format("Never mind."))
  entry20:add(entry21, dialogObject:format("Helmet (50 000 credits)"))
  entry20:add(entry25, dialogObject:format("Grapple Beam (100 000 credits)"))
  entry20:add(entry29, dialogObject:format("Flashlight (3 000 credits)"))
  entry20:add(entry33, dialogObject:format("Never mind."))

  dSys:add(factory)
  return dSys

end