/**
 * @fileoverview Lua Emitter
 *
 * Converts a ScriptDefinition into a complete, valid StarMade NPC Lua script.
 *
 * The emitter performs a depth-first walk of the dialog node tree,
 * collects all nodes and hooks, and generates:
 *   1. A file-level JSDoc comment
 *   2. Optional SQLite init block
 *   3. Optional preamble lines
 *   4. All hook function definitions
 *   5. The `create(dialogObject, bindings)` function with all node declarations,
 *      hook instantiations, add() and addReaction() calls, and factory assembly
 *
 * @author InitSysRev
 * @version 1.0.0
 */

import { ScriptDefinition } from '../core/ScriptDefinition.js';
import { DialogNode } from '../core/DialogNode.js';
import { HookDefinition } from '../core/Hook.js';
import { JAVA_CLASSES } from '../core/DialogObject.js';

// ── Placeholder substitution ──────────────────────────────────────────────────

/**
 * Converts TypeScript placeholder syntax to StarMade's dialogObject format().
 * {name}    → dialogObject:getConverationParterName()
 * {partner} → dialogObject:getConverationPartnerAffinity()
 * {faction} → dialogObject:getConverationPartnerFactionName()
 * {owner}   → dialogObject:getConverationPartnerOwnerName()
 * {self}    → dialogObject:getOwnName()
 */
function resolvePlaceholders(text: string): string {
  return text
    .replace(/\{name\}/g,    '%s')
    .replace(/\{partner\}/g, '%s')
    .replace(/\{faction\}/g, '%s')
    .replace(/\{owner\}/g,   '%s')
    .replace(/\{self\}/g,    '%s');
}

function formatArgs(text: string): string[] {
  const args: string[] = [];
  if (/\{name\}/.test(text))    args.push('dialogObject:getConverationParterName()');
  if (/\{partner\}/.test(text)) args.push('dialogObject:getConverationPartnerAffinity()');
  if (/\{faction\}/.test(text)) args.push('dialogObject:getConverationPartnerFactionName()');
  if (/\{owner\}/.test(text))   args.push('dialogObject:getConverationPartnerOwnerName()');
  if (/\{self\}/.test(text))    args.push('dialogObject:getOwnName()');
  return args;
}

function buildTextExpr(text: string, dialogObject = 'dialogObject'): string {
  const resolved = resolvePlaceholders(text);
  const args = formatArgs(text);
  if (args.length === 0) {
    return `${dialogObject}:format("${escapeLua(resolved)}")`;
  }
  return `${dialogObject}:format("${escapeLua(resolved)}", ${args.join(', ')})`;
}

function escapeLua(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

// ── Emitter ────────────────────────────────────────────────────────────────────

export class LuaEmitter {
  /**
   * Emit a complete Lua script from a ScriptDefinition.
   */
  static emit(script: ScriptDefinition): string {
    if (!script.root) throw new Error('LuaEmitter: ScriptDefinition has no root node');

    const lines: string[] = [];

    // File header
    lines.push(`--[[`);
    lines.push(`  ${script.description}`);
    lines.push(`  Generated by StarMade-NPCCreator`);
    lines.push(`  Script name: ${script.name}`);
    lines.push(`--]]`);
    lines.push(``);

    // SQLite init block
    if (script.db) {
      lines.push(script.db.emitInit());
      lines.push(``);
    }

    // Preamble
    if (script.preamble.length > 0) {
      lines.push(`-- Preamble`);
      for (const l of script.preamble) lines.push(l);
      lines.push(``);
    }

    // Collect all nodes (DFS)
    const allNodes = new Map<string, DialogNode>();
    const visited = new Set<DialogNode>();
    const collectNodes = (node: DialogNode) => {
      if (visited.has(node)) return;
      visited.add(node);
      allNodes.set(node.varName, node);
      for (const { target } of node.choices) collectNodes(target);
      for (const r of node.reactions) collectNodes(r.target);
    };
    collectNodes(script.root);

    // Collect all hooks referenced by any node
    const usedHooks = new Map<string, HookDefinition>();
    for (const node of allNodes.values()) {
      if (node.hook) usedHooks.set(node.hook.funcName, node.hook);
    }
    // Also include all registered hooks (for preamble-level hooks)
    for (const [name, hook] of script.hooks) {
      usedHooks.set(name, hook);
    }

    // Emit hook functions
    if (usedHooks.size > 0) {
      lines.push(`-- Hook functions`);
      for (const hook of usedHooks.values()) {
        const params = (hook.params && hook.params.length > 0)
          ? `, ${hook.params.join(', ')}`
          : '';
        lines.push(`function ${hook.funcName}(dialogObject${params})`);
        for (const bodyLine of hook.body) {
          lines.push(`  ${bodyLine}`);
        }
        lines.push(`end`);
        lines.push(``);
      }
    }

    // Main create() function
    lines.push(`function create(dialogObject, bindings)`);
    lines.push(``);
    lines.push(`  -- Bind Java dialog classes`);
    lines.push(`  local dSys = luajava.newInstance("${JAVA_CLASSES.DialogSystem}", dialogObject)`);
    lines.push(`  local factory = dSys:getFactory(bindings)`);
    lines.push(``);

    // Instantiate hook objects
    if (usedHooks.size > 0) {
      lines.push(`  -- Hook instances`);
      for (const hook of usedHooks.values()) {
        const paramsExpr = (hook.params && hook.params.length > 0)
          ? `{${hook.params.join(', ')}}`
          : '{}';
        lines.push(`  local hook_${hook.funcName} = luajava.newInstance("${JAVA_CLASSES.DialogTextEntryHookLua}", "${hook.funcName}", ${paramsExpr})`);
      }
      lines.push(``);
    }

    // Declare all TextEntry nodes
    lines.push(`  -- Dialog nodes`);
    for (const node of allNodes.values()) {
      const textExpr = buildTextExpr(node.text);
      lines.push(`  local ${node.varName} = luajava.newInstance("${JAVA_CLASSES.TextEntry}", ${textExpr}, ${node.displayMs})`);
      if (node.marking) {
        lines.push(`  ${node.varName}:setEntryMarking("${node.marking}")`);
      }
    }
    lines.push(``);

    // Set root entry
    lines.push(`  -- Root entry`);
    lines.push(`  factory:setRootEntry(${script.root.varName})`);
    lines.push(``);

    // Wire hooks
    const nodesWithHooks = [...allNodes.values()].filter(n => n.hook);
    if (nodesWithHooks.length > 0) {
      lines.push(`  -- Attach hooks`);
      for (const node of nodesWithHooks) {
        lines.push(`  ${node.varName}:setHook(hook_${node.hook!.funcName})`);
      }
      lines.push(``);
    }

    // Wire reactions
    const nodesWithReactions = [...allNodes.values()].filter(n => n.reactions.length > 0);
    if (nodesWithReactions.length > 0) {
      lines.push(`  -- Hook reactions`);
      for (const node of nodesWithReactions) {
        for (const r of node.reactions) {
          lines.push(`  ${node.varName}:addReaction(hook_${node.hook!.funcName}, ${r.code}, ${r.target.varName})`);
        }
      }
      lines.push(``);
    }

    // Wire choices (add calls)
    const nodesWithChoices = [...allNodes.values()].filter(n => n.choices.length > 0);
    if (nodesWithChoices.length > 0) {
      lines.push(`  -- Player choices`);
      for (const node of nodesWithChoices) {
        for (const { label, target } of node.choices) {
          const labelExpr = buildTextExpr(label);
          lines.push(`  ${node.varName}:add(${target.varName}, ${labelExpr})`);
        }
      }
      lines.push(``);
    }

    // Finalize
    lines.push(`  dSys:add(factory)`);
    lines.push(`  return dSys`);
    lines.push(``);
    lines.push(`end`);

    return lines.join('\n');
  }

  /**
   * Emit the script and return it as a string (alias for emit()).
   */
  static toLua(script: ScriptDefinition): string {
    return LuaEmitter.emit(script);
  }
}
